{% set name = "certbot-nginx" %}
{% set version = "5.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 592306f22162773083d378f85499b5c39c1c42d5fdfa23c42d7b52bbe1896c79

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - acme >=5.4.0
    - certbot >=5.4.0
    - pyopenssl >=25.0.0
    - pyparsing >=3.0.0
    - python >={{ python_min }}
    - setuptools >=41.6.0

test:
  imports:
    - certbot_nginx
    - certbot_nginx._internal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Nginx plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
