{% set name = "certbot-nginx" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4478c3e13e04b49f95675d83adaacdcf1356f8fac0824e236f893f2f5a1d991c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - acme >=4.0.0
    - certbot >=4.0.0
    - pyopenssl >=25.0.0
    - pyparsing >=2.4.7
    - python >={{ python_min }}
    - setuptools >=41.6.0

test:
  imports:
    - certbot_nginx
    - certbot_nginx._internal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Nginx plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
